{
  "👋 Hello there! *Voicy* is a voice recognition bot that converts all voice messages and audio files (.ogg, .flac, .wav, .mp3) it gets into text.\n\n*Voicy* supports three voice recognition engines: wit.ai (free), Yandex SpeechKit (free) and Google Speech (not free). Initialy it's set to use wit.ai but you can switch to Google Speech or Yandex SpeechKit anytime in /engine\n\nFor starters, you got *60 seconds* of Google Speech voice recognition for free. If you will need more Google Speech time, you can always purchase it here:\nhttps://pay.voicybot.com/$[1]\n\n...or just use free wit.ai or Yandex SpeechKit forever 😀": {
    "en": "👋 Hello there! *Voicy* is a voice recognition bot that converts all voice messages and audio files (.ogg, .flac, .wav, .mp3) it gets into text.\n\n*Voicy* supports three voice recognition engines: wit.ai (free), Yandex SpeechKit (free) and Google Speech (not free). Initialy it's set to use wit.ai but you can switch to Google Speech or Yandex SpeechKit anytime in /engine\n\nFor starters, you got *60 seconds* of Google Speech voice recognition for free. If you will need more Google Speech time, you can always purchase it here:\nhttps://pay.voicybot.com/$[1]\n\n...or just use free wit.ai or Yandex SpeechKit forever 😀",
    "ru": "👋 Привет! *Voicy* — это бот, который переводит в текст все голосовые сообщения и аудио файлы (.ogg, .flac, .wav, .mp3), которые получает.\n\n*Voicy* поддерживает три движка распознавания речи: wit.ai (бесплатный), Яндекс SpeechKit (бесплатный) и Google Speech (платный). Изначально бот выбирает бесплатный wit.ai, но вы можете сменить движок на Google Speech или Яндекс SpeechKit, используя команду /engine.\n\nДля ознакомления, мы даем вам *60 секунд* Google Speech в подарок. Если вам понадобится больше секунд Google Speech, вы всегда можете приобрести их по ссылке:\nhttps://pay.voicybot.com/$[1]\n\n...или просто используйте бесплатный wit.ai или Яндекс SpeechKit 😀",
    "es": "👋 ¡Hola! *Voicy* es un bot de reconocimiento de voz que convierte todos los mensajes de voz y archivos de audio (.ogg, .flac, .wav, .mp3) a texto.\n\n*Voicy* admite tres motores de reconocimiento de voz: wit.ai (gratuito), Yandex SpeechKit (gratuito) y Google Speech (pago). Inicialmente está configurado para usar wit.ai, pero puedes cambiarlo y utilizar Google Speech o Yandex SpeechKit en cualquier momento en /engine\n\npara principiantes, tienes *60 segundos* de reconocimiento de voz de Google Speech gratis. Si necesitas más tiempo de Google Speech, puedes comprarlo aquí:\nhttps://pay.voicybot.com/$[1]\n\n... o simplemente utilizar wit.ai o Yandex SpeechKit de forma gratuita para siempre 😀"
  },
  "👋 Hello there! *Voicy* is a voice recognition bot that converts all voice messages and audio files (.ogg, .flac, .wav, .mp3) it gets into text.\n\n*Voicy* supports three voice recognition engines: wit.ai (free), Yandex SpeechKit (free) and Google Speech (not free). Initialy it's set to use wit.ai but you can switch to Google Speech or Yandex SpeechKit anytime in /engine\n\nSo far you have *$[1] seconds* of Google Speech voice recognition left. If you will need more Google Speech time, you can always purchase it here:\nhttps://pay.voicybot.com/$[2]\n\n...or just use free wit.ai or Yandex SpeechKit forever 😀": {
    "en": "👋 Hello there! *Voicy* is a voice recognition bot that converts all voice messages and audio files (.ogg, .flac, .wav, .mp3) it gets into text.\n\n*Voicy* supports three voice recognition engines: wit.ai (free), Yandex SpeechKit (free) and Google Speech (not free). Initialy it's set to use wit.ai but you can switch to Google Speech or Yandex SpeechKit anytime in /engine\n\nSo far you have *$[1] seconds* of Google Speech voice recognition left. If you will need more Google Speech time, you can always purchase it here:\nhttps://pay.voicybot.com/$[2]\n\n...or just use free wit.ai or Yandex SpeechKit forever 😀",
    "ru": "👋 Привет! *Voicy* — это бот, который переводит в текст все голосовые сообщения и аудио файлы (.ogg, .flac, .wav, .mp3), которые получает.\n\n*Voicy* поддерживает три движка распознавания речи: wit.ai (бесплатный), Яндекс SpeechKit (бесплатный) и Google Speech (платный). Изначально бот выбирает бесплатный wit.ai, но вы можете сменить движок на Google Speech или Яндекс SpeechKit, используя команду /engine.\n\nУ вас осталось *$[1] секунд* Google Speech в этом чате. Если вам понадобится больше секунд Google Speech, вы всегда можете приобрести их по ссылке:\nhttps://pay.voicybot.com/$[2]\n\n...или просто используйте бесплатный wit.ai или Яндекс SpeechKit 😀",
    "es": "👋 ¡Hola! *Voicy* es un bot de reconocimiento de voz que convierte todos los mensajes de voz y archivos de audio (.ogg, .flac, .wav, .mp3) a texto.\n\n*Voicy* admite tres motores de reconocimiento de voz: wit.ai (gratuito), Yandex SpeechKit (gratuito) y Google Speech (pago). Inicialmente está configurado para usar wit.ai pero puedes cambiarlo y utilizar Google Speech o Yandex SpeechKit en cualquier momento en /engine\n\nTendrás *$[1] segundos* de reconocimiento de voz de Google Speech. Si necesitas más tiempo de Google Speech, siempre puedes comprarlo aquí:\nhttps://pay.voicybot.com/$[2]\n\n ... o simplemente utilizar wit.ai o Yandex SpeechKit de manera gratuita para siempre 😀"
  },
  "🎉 Unfortunately, being the most superior voice recognition engine, Google Speech is not free. If you want to keep using free wit.ai or Yandex SpeechKit for voice recognition, no need to do anything. However, if you want to use Google Speech you have to cover it's costs.\n\nThis chat has *$[1] seconds* of Google Speech voice recognition left.\n\nAnybody can buy more Google Speech seconds for the price of *$0.4 per 200 seconds* here:\nhttps://pay.voicybot.com/$[2].": {
    "en": "🎉 Unfortunately, being the most superior voice recognition engine, Google Speech is not free. If you want to keep using free wit.ai or Yandex SpeechKit for voice recognition, no need to do anything. However, if you want to use Google Speech you have to cover it's costs.\n\nThis chat has *$[1] seconds* of Google Speech voice recognition left.\n\nAnybody can buy more Google Speech seconds for the price of *$0.4 per 200 seconds* here:\nhttps://pay.voicybot.com/$[2].",
    "ru": "🎉 К сожалению, Google Speech — более точный переводчик речи в текст — не бесплатен. Если вы хотите и дальше использовать бесплатные wit.ai или Яндекс SpeechKit — просто проигнорируйте это сообщение. Однако если вы хотите использовать Google Speech, вам придётся оплатить стоимость распознавания.\n\nУ этого чата осталось еще *$[1] секунд* Google Speech.\n\nКто угодно может купить больше секунд Google Speech по цене *$0.4 за 200 секунд* по ссылке:\nhttps://pay.voicybot.com/$[2].",
    "es": "🎉 Desafortunadamente, pese a ser el mejor motor de reconocimiento de voz, Google Speech no es gratuito. Si quieres seguir usando wit.ai o Yandex SpeechKit gratuitos para reconocimiento de voz, no tienes necesidad de hacer nada. Sin embargo, si quieres usar Google Speech, tienes que cubrir sus costos. \n\nEste chat tiene *$[1] segundos* de reconocimiento de voz de Google Speech.\n\nCualquier persona puede comprar más segundos de Google Speech por el precio de *$0.4 por cada 200 segundos* aquí: \nhttps://pay.voicybot.com/$[2]."
  },
  "🎉 Unfortunately, being the most superior voice recognition engine, Google Speech is not free. If you want to switch to free wit.ai or Yandex SpeechKit for voice recognition, please do so in /engine. However, if you want to stick to Google Speech you have to cover it's costs.\n\nThis chat has *$[1] seconds* of Google Speech voice recognition left.\n\nAnybody can buy more Google Speech seconds for the price of *$0.4 per 200 seconds* here:\nhttps://pay.voicybot.com/$[2].": {
    "en": "🎉 Unfortunately, being the most superior voice recognition engine, Google Speech is not free. If you want to switch to free wit.ai or Yandex SpeechKit for voice recognition, please do so in /engine. However, if you want to stick to Google Speech you have to cover it's costs.\n\nThis chat has *$[1] seconds* of Google Speech voice recognition left.\n\nAnybody can buy more Google Speech seconds for the price of *$0.4 per 200 seconds* here:\nhttps://pay.voicybot.com/$[2].",
    "ru": "🎉 К сожалению, Google Speech — более точный переводчик речи в текст — не бесплатен. Если вы хотите перейти на бесплатный wit.ai или Яндекс SpeechKit — используйте команду /engine. Однако если вы хотите продолжить использовать Google Speech, вам придётся оплатить стоимость распознавания.\n\nУ этого чата осталось еще *$[1] секунд* Google Speech.\n\nКто угодно может купить больше секунд Google Speech по цене *$0.4 за 200 секунд* по ссылке:\nhttps://pay.voicybot.com/$[2].",
    "es": "🎉 Desafortunadamente, pese a ser el mejor motor de reconocimiento de voz, Google Speech no es gratuito. Si quieres cambiar a wit.ai o Yandex SpeechKit gratuitos para reconocimiento de voz, por favor hazlo en /engine. Sin embargo, si quieres quedarte con Google Speech tienes que cubrir sus costos. \n\nEste chat tiene *$[1] segundos* de reconocimiento de voz de Google Speech.\n\nCualquier persona puede comprar más segundos de Google Speech por el precio de *$0.4 por cada 200 segundos* aquí :\nhttps://pay.voicybot.com/$[2]."
  },
  "😮 It looks like this chat has *no more seconds* of Google Speech voice recognition left! But no worries — we have automatically switched you to the free wit.ai so that no voice messages are getting lost. Don't forget to setup your /language.\n\nHowever if you would like to keep using Google Speech you will have to switch back in /engine and cover it's costs 💰\n\nAnybody can buy more seconds for the price of *$0.4 per 200 seconds* here:\nhttps://pay.voicybot.com/$[1].": {
    "en": "😮 It looks like this chat has *no more seconds* of Google Speech voice recognition left! But no worries — we have automatically switched you to the free wit.ai so that no voice messages are getting lost. Don't forget to setup your /language.\n\nHowever if you would like to keep using Google Speech you will have to switch back in /engine and cover it's costs 💰\n\nAnybody can buy more seconds for the price of *$0.4 per 200 seconds* here:\nhttps://pay.voicybot.com/$[1].",
    "ru": "😮 Похоже, у этого чата больше *нет секунд* Google Speech! Но ничего страшного — мы автоматически перевели вас на бесплатный wit.ai, чтобы не потерять ни одного голосового сообщения. Обязательно установите язык командой /language!\n\nОднако если вы хотите продолжить использовать Google Speech, вам нужно сменить движок командой /engine и оплатить стоимость распознавания 💰\n\nКто угодно может купить больше секунд Google Speech по цене *$0.4 за 200 секунд* по ссылке:\nhttps://pay.voicybot.com/$[1].",
    "es": "😮 ¡Parece que este chat no tiene *más segundos* de reconocimiento de voz de Google Speech! Pero no te preocupes – te hemos cambiado automáticamente a wit.ai gratuito para que no se pierda ningún mensajes de voz. No olvides configurar tu /language.\n\nSin embargo, si quieres seguir usando Google Speech deberás cambiar nuevamente en /engine y cubrir sus costos 💰\n\nCualquier persona puede comprar más segundos de Google Speech por el precio de *$0.4 por cada 200 segundos* aquí \nhttps://pay.voicybot.com/$[1]."
  },
  "😎 *Voicy* converts speech to text from any voice messages and audio files (.ogg, .flac, .wav, .mp3) it receives. You can either talk to *Voicy* in the private chat or add it to a group.\n\n/help — Shows this message 😱\n/engine — Lets you pick a voice recognition engine: wit.ai (free), Yandex SpeechKit (free) or Google Speech (not free) ⚙\n/language — Lets you pick a voice recognition language 📣\n/balance — Shows how many Google Speech voice recognition seconds are left for this chat 🎉\n/files — Toggles if the bot should attempt to convert audio files or just ignore them 📁\n/silent — Toggles silent mode when no extra messages like `Voice recognition is initiated` are sent 😶\n\nLike this bot? Leave a review here: https://telegram.me/storebot?start=voicybot\n\nAddress any concerns and questions to my creator — @borodutch 🦄": {
    "en": "😎 *Voicy* converts speech to text from any voice messages and audio files (.ogg, .flac, .wav, .mp3) it receives. You can either talk to *Voicy* in the private chat or add it to a group.\n\n/help — Shows this message 😱\n/engine — Lets you pick a voice recognition engine: wit.ai (free), Yandex SpeechKit (free) or Google Speech (not free) ⚙\n/language — Lets you pick a voice recognition language 📣\n/balance — Shows how many Google Speech voice recognition seconds are left for this chat 🎉\n/files — Toggles if the bot should attempt to convert audio files or just ignore them 📁\n/silent — Toggles silent mode when no extra messages like `Voice recognition is initiated` are sent 😶\n\nLike this bot? Leave a review here: https://telegram.me/storebot?start=voicybot\n\nAddress any concerns and questions to my creator — @borodutch 🦄",
    "ru": "😎 *Voicy* переводит в текст все голосовые сообщения, которые получает. Вы можете говорить с ботом напрямую или добавить его в группу.\n\n/help — Показать это сообщение 😱\n/engine — Выбрать движок распознавания речи: wit.ai (бесплатный), Яндекс SpeechKit (бесплатный) или Google Speech (платный) ⚙\n/language — Выбрать язык распознавания речи 📣\n/balance — Посмотреть, сколько секунд Google Speech осталось 🎉\n/files — Включить или выключить распознавание аудио файлов 📁\n/silent — Включить или выключить тихий режим, когда бот не посылает сообщения типа `Распознавание речи инициировано` 😶\n\nНравится бот? Оставьте свой отзыв по ссылке: https://telegram.me/storebot?start=voicybot\n\nВопросы и предложения направляйте моему создателю — @borodutch 🦄",
    "es": "😎 *Voicy* convierte discurso a texto desde cualquier mensaje de voz y archivos de audio (.ogg, .flac, .wav, .mp3) que reciba. Puede hablar con *Voicy* en un chat privado o agregarlo a un grupo.\n\n/help - Muestra este mensaje 😱\n/engine - Permite elegir un motor de reconocimiento de voz: wit.ai (gratuito), Yandex SpeechKit (gratuito) o Google Speech (pago) - Permite seleccionar el idioma de reconocimiento de voz 📣\n/balance - Muestra cuántos segundos de reconocimiento de voz de Google Speech quedan para este chat 🎉\n/files - Cambia si el bot intenta convertir archivos de audio o simplemente ignorarlos 📁\n/silent - Cambia el modo silencioso cuando no se envían mensajes adicionales como \"Reconocimiento de voz\" 😶\n\nTe gusta este bot? Deja un comentario aquí: https://telegram.me/storebot?start=voicybot\n\nEnviar cualquier duda o consulta a mi creador - @borodutch 🦄"
  },
  "😎 *Voicy* converts speech to text from any voice messages and audio files (.ogg, .flac, .wav, .mp3) it receives. You can either talk to *Voicy* in the private chat or add it to a group.\n\n/help — Shows this message 😱\n/engine — Lets you pick a voice recognition engine: wit.ai (free), Yandex SpeechKit (free) or Google Speech (not free) ⚙\n/language — Lets you pick a voice recognition language 📣\n/balance — Shows how many Google Speech voice recognition seconds are left for this chat 🎉\n/lock — Toggles lock or unlock of non-admins using commands 🔑\n/files — Toggles if the bot should attempt to convert audio files or just ignore them 📁\n/silent — Toggles silent mode when no extra messages like `Voice recognition is initiated` are sent 😶\n\nLike this bot? Leave a review here: https://telegram.me/storebot?start=voicybot\n\nAddress any concerns and questions to my creator — @borodutch 🦄": {
    "en": "😎 *Voicy* converts speech to text from any voice messages and audio files (.ogg, .flac, .wav, .mp3) it receives. You can either talk to *Voicy* in the private chat or add it to a group.\n\n/help — Shows this message 😱\n/engine — Lets you pick a voice recognition engine: wit.ai (free), Yandex SpeechKit (free) or Google Speech (not free) ⚙\n/language — Lets you pick a voice recognition language 📣\n/balance — Shows how many Google Speech voice recognition seconds are left for this chat 🎉\n/lock — Toggles lock or unlock of non-admins using commands 🔑\n/files — Toggles if the bot should attempt to convert audio files or just ignore them 📁\n/silent — Toggles silent mode when no extra messages like `Voice recognition is initiated` are sent 😶\n\nLike this bot? Leave a review here: https://telegram.me/storebot?start=voicybot\n\nAddress any concerns and questions to my creator — @borodutch 🦄",
    "ru": "😎 *Voicy* переводит в текст все голосовые сообщения, которые получает. Вы можете говорить с ботом напрямую или добавить его в группу.\n\n/help — Показать это сообщение 😱\n/engine — Выбрать движок распознавания речи: wit.ai (бесплатный), Яндекс SpeechKit (бесплатный) или Google Speech (платный) ⚙\n/language — Выбрать язык распознавания речи 📣\n/balance — Посмотреть, сколько секунд Google Speech осталось 🎉\n/lock — Включить или выключить доступ не-админов к командам бота 🔑\n/files — Включить или выключить распознавание аудио файлов 📁\n\n/silent — Включить или выключить тихий режим, когда бот не посылает сообщения типа `Распознавание речи инициировано` 😶\n\nНравится бот? Оставьте свой отзыв по ссылке: https://telegram.me/storebot?start=voicybot\n\nВопросы и предложения направляйте моему создателю — @borodutch 🦄",
    "es": "😎 *Voicy* convierte discurso a texto desde cualquier mensaje de voz y archivos de audio (.ogg, .flac, .wav, .mp3) que reciba. Puede hablar con *Voicy* en un chat privado o agregarlo a un grupo.\n\n/help - Muestra este mensaje 😱\n/engine - Permite elegir un motor de reconocimiento de voz: wit.ai (gratuito), Yandex SpeechKit (gratuito) o Google Speech (pago) - Permite seleccionar el idioma de reconocimiento de voz  📣\n/balance - Muestra cuántos segundos de reconocimiento de voz de Google Speech quedan para este chat 🎉\n/lock - Cambia el bloqueo o desbloqueo de los no administradores que usan comandos 🔑\n/files - El bot debería intentar convertir archivos de audio o simplemente ignorarlos 📁\n/silent - Cambia el modo silencioso cuando no se envían mensajes adicionales como “Reconocimiento de voz” 😶\n\nTe gusta este bot? Deja un comentario aquí: https: /telegram.me/storebot?start=voicybot\n\nEnviar cualquier consulta duda o consulta a mi creador - @borodutch 🦄"
  },
  "👋 Please, select the engine of speech recognition. Google Speech is more accurate, private (your messages will never go public), support audio longer than 50 seconds, but not free. Yandex SpeechKit is pretty accurate, free, private and most of the time supports audio longer than 50 seconds, but has limited list of languages. Wit.ai is less accurate, public (your messages go to wit.ai public database), free, but doesn't support audio longer than 50 seconds.\n\nHere is the list of the supported languages:\n\n*wit.ai*: `Albanian, Arabic, Bengali, Bosnian, Bulgarian, Burmese, Catalan, Chinese, Croatian, Czech, Danish, Dutch, English, Estonian, Finnish, French, Georgian, German, Greek, Hebrew, Hindi, Hungarian, Icelandic, Indonesian, Italian, Japanese, Korean, Latin, Lithuanian, Macedonian, Malay, Norwegian, Persian, Polish, Portuguese, Romanian, Russian, Serbian, Slovak, Slovenian, Spanish, Swahili, Swedish, Tagalog, Tamil, Thai, Turkish, Ukrainian and Vietnamese`.\n\n*Yandex SpeechKit*: `Russian, English, Turkish, Ukrainian`.\n\n*Google Speech*: `Afrikaans, Indonesian, Malay, Catalan, Czech, Danish, German, English (Australia, Canada, United Kingdom, India, Ireland, New Zealand, Philippines, South Africa, United States), Spanish (Argentina, Bolivia, Chile, Colombia, Costa Rica, Ecuador, El Salvador, Spain, United States, Guatemala, Honduras, Mexico, Nicaragua, Panama, Paraguay, Peru, Puerto Rico, Dominican Republic, Uruguay, Venezuela), Basque,  Filipino, French, Galician, Croatian, Zulu, Icelandic, Italian, Lithuanian, Hungarian, Dutch, Norwegian Bokmål, Polish, Portuguese (Brazil, Portugal), Romanian, Slovak, Slovenian, Finnish, Swedish, Vietnamese, Turkish, Greek, Bulgarian, Russian, Serbian, Ukrainian, Hebrew, Arabic (Israel, Jordan, United Arab Emirates, Bahrain, Algeria, Saudi Arabia, Iraq, Kuwait, Morocco, Tunisia, Oman, State of Palestine, Qatar, Lebanon, Egypt), Persian, Hindi, Thai, Korean, Mandarin (Traditional, Taiwan; Simplified, Hong Kong; Simplified, China), Cantonese (Traditional, Hong Kong), Japanese (Japan)`.": {
    "en": "👋 Please, select the engine of speech recognition. Google Speech is more accurate, private (your messages will never go public), support audio longer than 50 seconds, but not free. Yandex SpeechKit is pretty accurate, free, private and most of the time supports audio longer than 50 seconds, but has limited list of languages. Wit.ai is less accurate, public (your messages go to wit.ai public database), free, but doesn't support audio longer than 50 seconds.\n\nHere is the list of the supported languages:\n\n*wit.ai*: `Albanian, Arabic, Bengali, Bosnian, Bulgarian, Burmese, Catalan, Chinese, Croatian, Czech, Danish, Dutch, English, Estonian, Finnish, French, Georgian, German, Greek, Hebrew, Hindi, Hungarian, Icelandic, Indonesian, Italian, Japanese, Korean, Latin, Lithuanian, Macedonian, Malay, Norwegian, Persian, Polish, Portuguese, Romanian, Russian, Serbian, Slovak, Slovenian, Spanish, Swahili, Swedish, Tagalog, Tamil, Thai, Turkish, Ukrainian and Vietnamese`.\n\n*Yandex SpeechKit*: `Russian, English, Turkish, Ukrainian`.\n\n*Google Speech*: `Afrikaans, Indonesian, Malay, Catalan, Czech, Danish, German, English (Australia, Canada, United Kingdom, India, Ireland, New Zealand, Philippines, South Africa, United States), Spanish (Argentina, Bolivia, Chile, Colombia, Costa Rica, Ecuador, El Salvador, Spain, United States, Guatemala, Honduras, Mexico, Nicaragua, Panama, Paraguay, Peru, Puerto Rico, Dominican Republic, Uruguay, Venezuela), Basque,  Filipino, French, Galician, Croatian, Zulu, Icelandic, Italian, Lithuanian, Hungarian, Dutch, Norwegian Bokmål, Polish, Portuguese (Brazil, Portugal), Romanian, Slovak, Slovenian, Finnish, Swedish, Vietnamese, Turkish, Greek, Bulgarian, Russian, Serbian, Ukrainian, Hebrew, Arabic (Israel, Jordan, United Arab Emirates, Bahrain, Algeria, Saudi Arabia, Iraq, Kuwait, Morocco, Tunisia, Oman, State of Palestine, Qatar, Lebanon, Egypt), Persian, Hindi, Thai, Korean, Mandarin (Traditional, Taiwan; Simplified, Hong Kong; Simplified, China), Cantonese (Traditional, Hong Kong), Japanese (Japan)`.",
    "ru": "👋 Выберите движок распознавания речи. Google Speech — более точный, приватный (ваши сообщения никогда не станут достоянием общественности), поддерживает аудио длиннее 50 секунд, но не бесплатный. Яндекс SpeechKit — поддерживает аудио длиннее 50 секунд, беслпатный, приватный, но с ограниченным количеством языков. Wit.ai — менее точный, публичный (данные хранятся в открытом доступе на wit.ai), не поддерживает аудио длиннее 50 секунд, но бесплатный.\n\nСписки поддерживаемых языков:\n\n*wit.ai*: `Albanian, Arabic, Bengali, Bosnian, Bulgarian, Burmese, Catalan, Chinese, Croatian, Czech, Danish, Dutch, English, Estonian, Finnish, French, Georgian, German, Greek, Hebrew, Hindi, Hungarian, Icelandic, Indonesian, Italian, Japanese, Korean, Latin, Lithuanian, Macedonian, Malay, Norwegian, Persian, Polish, Portuguese, Romanian, Russian, Serbian, Slovak, Slovenian, Spanish, Swahili, Swedish, Tagalog, Tamil, Thai, Turkish, Ukrainian, Vietnamese`.\n\n*Яндекс SpeechKit*: `Russian, English, Turkish, Ukrainian`.\n\n*Google Speech*: `Afrikaans, Indonesian, Malay, Catalan, Czech, Danish, German, English (Australia, Canada, United Kingdom, India, Ireland, New Zealand, Philippines, South Africa, United States), Spanish (Argentina, Bolivia, Chile, Colombia, Costa Rica, Ecuador, El Salvador, Spain, United States, Guatemala, Honduras, Mexico, Nicaragua, Panama, Paraguay, Peru, Puerto Rico, Dominican Republic, Uruguay, Venezuela), Basque,  Filipino, French, Galician, Croatian, Zulu, Icelandic, Italian, Lithuanian, Hungarian, Dutch, Norwegian Bokmål, Polish, Portuguese (Brazil, Portugal), Romanian, Slovak, Slovenian, Finnish, Swedish, Vietnamese, Turkish, Greek, Bulgarian, Russian, Serbian, Ukrainian, Hebrew, Arabic (Israel, Jordan, United Arab Emirates, Bahrain, Algeria, Saudi Arabia, Iraq, Kuwait, Morocco, Tunisia, Oman, State of Palestine, Qatar, Lebanon, Egypt), Persian, Hindi, Thai, Korean, Mandarin (Traditional, Taiwan; Simplified, Hong Kong; Simplified, China), Cantonese (Traditional, Hong Kong), Japanese (Japan)`.",
    "es": "👋 Por favor, selecciona el motor del reconocimiento de voz: Google Speech es más preciso, privado (tus mensajes nunca serán públicos), soporta audios de más de 50 segundos, pero no es gratuito. Yandex SpeechKit es bastante preciso, gratuito, privado y casi siempre es compatible audios de más de 50 segundos, pero tiene una lista limitada de idiomas. Wit.ai es menos preciso, público (tus mensajes van a la base de datos pública de wit.ai), es gratuito pero no es compatible con audios de más de 50 segundos. \n\nEsta es la lista de idiomas disponibles:\n\n*wit.ai*: `albanés, árabe, bengalí, bosnio, búlgaro, birmano, catalán, chino, croata, checo, danés, holandés, inglés, estonio, Finlandés, francés, georgiano, griego, hebreo, hindi, húngaro, islandés, indonesio, italiano, japonés, coreano, latín, lituano, macedonio, malayo, noruego, persa, polaco, Portugués, rumano, ruso, serbio, eslovaco, esloveno, español, swahili, sueco, tagalo, tamil, tailandés, turco, ucraniano y vietnamita`.\n\n*Yandex SpeechKit*: `Ruso, Inglés, Turco, Ucraniano`.\n\n*Google Speech*: `Español, Sueco, Tagalo, Tamil, Afrikáans, Indonesio, Malayo, Catalán, Checo, Danés, Alemán, Inglés (Australia, Canadá, Reino Unido, India, Irlanda, Nueva Zelanda, Filipinas, Sudáfrica, Estados Unidos), Español (Argentina, Bolivia, Chile, Colombia, Costa Ecuador, Ecuador, El Salvador, España, Guatemala, Honduras, México, Nicaragua, Panamá, Paraguay, Perú, Puerto Rico, República Dominicana, Uruguay, Venezuela), Vasco, Filipino, Gallego, Croata, Zulú, Islandés, Italiano, Lituano, Húngaro, Holandés, Noruego Bokmål, Polaco, Portugués (Brasil, Portugal),Rumano, Esloveno, Esloveno, Finlandés, Sueco, Vietnamita, Turco, Griego, Búlgaro, Ruso, Serbio, Ucraniano, Hebreo, Árabe (Israel, Jordania, Emiratos Árabes Unidos, Bahreiní, Argelia, Iraq, Kuwait, Marruecos, Túnez , Tailandia, Coreano, Mandarín (Tradicional, Taiwán, Simplificado, Hong Kong, Simplificado, China), Cantonés (Tradicional, Hong Kong), Japonés (Japón)`."
  },
  "👍 Now *Voicy* uses *$[1]* in this chat. Thank you! Don't forget to set /language.": {
    "en": "👍 Now *Voicy* uses *$[1]* in this chat. Thank you! Don't forget to set /language.",
    "ru": "👍 Теперь *Voicy* использует *$[1]* в этом чате. Спасибо! Не забудьте установить /language (язык).",
    "es": "👍 Ahora *Voicy* utiliza *$[1]* en este chat. ¡Gracias!, No te olvides configurar /language."
  },
  "👋 Please select the language of speech recognition": {
    "en": "👋 Please select the language of speech recognition",
    "ru": "👋 Выберите язык распознавания речи",
    "es": "👋 Por favor, seleccione el idioma de reconocimiento de voz"
  },
  "👋 Please select the language of speech recognition for $[1].": {
    "en": "👋 Please, select the language of speech recognition for $[1].",
    "ru": "👋 Выберите язык распознавания речи для $[1].",
    "es": "👋 Por favor, seleccione el idioma de reconocimiento de voz para $[1]."
  },
  "👋 Please select the language of speech recognition for wit.ai.": {
    "en": "👋 Please, select the language of speech recognition for wit.ai.",
    "ru": "👋 Выберите язык распознавания речи для wit.ai.",
    "es": "👋 Por favor, seleccione el idioma de reconocimiento de voz para wit.ai."
  },
  "👍 Now *Voicy* speaks *$[1]* (wit.ai) in this chat. Thank you!": {
    "en": "👍 Now *Voicy* speaks *$[1]* (wit.ai) in this chat. Thank you!",
    "ru": "👍 Теперь *Voicy* понимает *$[1]* (wit.ai) в этом чате. Спасибо!",
    "es": "👍 Ahora *Voicy* habla *$[1]* (wit.ai) en este chat. ¡Gracias!"
  },
  "👋 Please select the language of speech recognition for Google Speech.": {
    "en": "👋 Please, select the language of speech recognition for Google Speech.",
    "ru": "👋 Выберите язык распознавания речи для Google Speech.",
    "es": "👋 Por favor, seleccione el idioma de reconocimiento de voz para Google Speech."
  },
  "👍 Now *Voicy* speaks *$[1]* (Google Speech) in this chat. Thank you!": {
    "en": "👍 Now *Voicy* speaks *$[1]* (Google Speech) in this chat. Thank you!",
    "ru": "👍 Теперь *Voicy* понимает *$[1]* (Google Speech) в этом чате. Спасибо!",
    "es": "👍  Ahora *Voicy* habla *$[1]* (Google Speech) en este chat. ¡Gracias!"
  },
  "👍 Now *Voicy* speaks *$[1]* (Yandex SpeechKit) in this chat. Thank you!": {
    "en": "👍 Now *Voicy* speaks *$[1]* (Yandex SpeechKit) in this chat. Thank you!",
    "ru": "👍 Теперь *Voicy* понимает *$[1]* (Яндекс SpeechKit) в этом чате. Спасибо!",
    "es": "👍 Ahora *Voicy* habla *$[1]* (Yandex SpeechKit) en este chat. ¡Gracias!"
  },
  "😮 You didn't have enough seconds of Google Speech voice recognition left to convert this voice message! But no worries — we have automatically switched you to the free wit.ai so that no voice messages are getting lost. Don't forget to setup your /language.": {
    "en": "😮 You didn't have enough seconds of Google Speech voice recognition left to convert this voice message! But no worries — we have automatically switched you to the free wit.ai so that no voice messages are getting lost. Don't forget to setup your /language.",
    "ru": "😮 У вас не хватило секунд Google Speech для распознавания этого голосового сообщения! Но ничего страшного — мы автоматически перели ваш чат на бесплатный wit.ai, чтобы не потерять ни одного сообщения. Не забудьте указать ваш язык командой /language!",
    "es": "😮 ¡No tenías suficientes segundos de reconocimiento de voz de Google Speech para convertir este mensaje de voz!, pero no te preocupes: te hemos cambiado automáticamente a wit.ai para que no se pierda ningún mensajes de voz. No te olvides de configurar tu /language."
  },
  "_👮 I can't recognize voice messages larger than 20 megabytes_": {
    "en": "_👮 I can't recognize voice messages larger than 20 megabytes_",
    "ru": "_👮 Я не умею распознавать аудио тяжелее 20 мегабайт_",
    "es": "_👮 No puedo reconocer mensajes de voz mayores a 20 megabytes_"
  },
  "_🦄 Voice recognition is initiated..._": {
    "en": "_🦄 Voice recognition is initiated..._",
    "ru": "_🦄 Распознавание речи инициировано..._",
    "es": "_🦄 Se inicia el reconocimiento de voz..._"
  },
  "_👮 Please, speak clearly, I couldn't recognize that_": {
    "en": "_👮 Please, speak clearly, I couldn't recognize that._",
    "ru": "_👮 Пожалуйста, говорите четче, у меня не получилось распознать вашу речь._",
    "es": "_👮 Por favor, habla con claridad, no pude reconocer eso_"
  },
  "_👮 I couldn't recognize that_": {
    "en": "_👮 I couldn't recognize that._",
    "ru": "_👮 У меня не получилось распознать речь._",
    "es": "_👮 No pude reconocer eso_"
  },
  "😅 Looks like you have already applied Product Hunt discount. Your first 100,000 Google Speech seconds are 50% off. Enjoy! 🐱": {
    "en": "😅 Looks like you have already applied Product Hunt discount. Your first 100,000 Google Speech seconds are 50% off. Enjoy! 🐱",
    "ru": "😅 Похоже, вы уже использовали скидку с Product Hunt. Ваши первые 100,000 Google Speech секунд уже на 50% дешевле. Спасибо! 🐱",
    "es": "😅 Parece que ya has aplicado el descuento de Product Hunt. Los primeros 100.000 segundos de Google Speech tiene 50% de descuento. ¡Disfruta! 🐱"
  },
  "🔥 Look who applied Product Hunt discount to @voicybot! Enjoy your first 100,000 Google Speech seconds at 50% the price! 🦄": {
    "en": "🔥 Look who applied Product Hunt discount to @voicybot! Enjoy your first 100,000 Google Speech seconds at 50% the price! 🦄",
    "ru": "🔥 Смотрите, кто использовал скидку с Product Hunt в @voicybot! Наслаждайтесь первыми 100,000 секундами распознавания Google Speech с 50% скидкой! 🦄",
    "es": "🔥 ¡Mira quién aplicó el descuento de Product Hunt a @voicybot! ¡Disfruta de tus primeros 100.000 segundos de Google Speech al 50% del precio! 🦄"
  },
  "🔑 Great! *Voicy* will now respond only to command calls sent by *admins* in this chat.": {
    "en": "🔑 Great! *Voicy* will now respond only to command calls sent by *admins* in this chat.",
    "ru": "🔑 Чудно! *Voicy* теперь реагирует только на команды, посланные *админами*, в этом чате.",
    "es": "🔑 ¡Genial! *Voicy* ahora responderá sólo a las llamadas de comando enviadas por *admins* en este chat."
  },
  "🔑 Great! *Voicy* will now respond only to command calls from *anyone* in this chat.": {
    "en": "🔑 Great! *Voicy* will now respond only to command calls from *anyone* in this chat.",
    "ru": "🔑 Чудно! *Voicy* теперь реагирует на команды, посланные *любыми пользователями*, в этом чате.",
    "es": "🔑 ¡Genial! *Voicy* ahora responderá sólo a las llamadas de comando de *cualquier persona* en este chat."
  },
  "😶 Magnificent! *Voicy* will now work in *silent mode*: it will not send any messages to the chat except for the actual voice transcriptions.": {
    "en": "😶 Magnificent! *Voicy* will now work in *silent mode*: it will not send any messages to the chat except for the actual voice transcriptions.",
    "ru": "😶 Великолепно! *Voicy* теперь работает в *тихом режиме*: больше никаких сообщений, кроме перевода речи в текст.",
    "es": "😶 ¡Magnífico! *Voicy* ahora funcionará en *modo silencioso*: no enviará ningún mensaje al chat, excepto las transcripciones de voz reales."
  },
  "😏 Magnificent! *Voicy* will now work in *usual mode*: it will send `Voice recognition is initiated` messages right after it receives voice messages.": {
    "en": "😏 Magnificent! *Voicy* will now work in *usual mode*: it will send `Voice recognition is initiated` messages right after it receives voice messages.",
    "ru": "😏 Великолепно! *Voicy* теперь работает в *обычном режиме*: бот будет посылать промежуточное сообщение `Распознавание речи инициировано` после каждого полученного голосового сообщения.",
    "es": "😏 ¡Magnífico! *Voicy* funcionará ahora en *modo habitual*: enviará mensajes de \"Reconocimiento de voz iniciado” inmediatamente luego de recibir mensajes de voz"
  },
  "_👮 Wit.ai cannot recognize voice messages longer than 50 seconds_": {
    "en": "_👮 Wit.ai cannot recognize voice messages longer than 50 seconds_",
    "ru": "_👮 Wit.ai не понимает аудио длиннее 50 секунд_",
    "es": "_👮 Wit.ai no puede reconocer mensajes de voz de más de 50 segundos_"
  },
  "📁 Wonderful! *Voicy* will *ignore* all audio files in this chat since now.": {
    "en": "📁 Wonderful! *Voicy* will *ignore* all audio files in this chat since now.",
    "ru": "📁 Отлично! *Voicy* теперь будет *игнорировать* все аудио файлы в этом чате.",
    "es": "📁 ¡Maravilloso! Desde ahora *Voicy ignorará* todos los archivos de audio en este chat."
  },
  "📁 Wonderful! *Voicy* will *try to recognize* all audio files in this chat since now.": {
    "en": "📁 Wonderful! *Voicy* will *try to recognize* all audio files in this chat since now.",
    "ru": "📁 Отлично! *Voicy* теперь будет *пробовать распознать* все аудио файлы в этом чате.",
    "es": "📁 ¡Maravilloso! Desde ahora *Voicy* *intentará reconocer* todos los archivos de audio en este chat."
  }
}