{
  "👋 Hello there! *Voicy* is a voice recognition bot that converts all voice messages and audio files (.ogg, .flac, .wav, .mp3) it gets into text.\n\n*Voicy* supports three voice recognition engines: wit.ai (free), Yandex SpeechKit (free) and Google Speech (not free). Initialy it's set to use wit.ai but you can switch to Google Speech or Yandex SpeechKit anytime in /engine\n\nFor starters, you got *60 seconds* of Google Speech voice recognition for free. If you will need more Google Speech time, you can always purchase it here:\nhttps://pay.voicybot.com/$[1]\n\n...or just use free wit.ai or Yandex SpeechKit forever 😀": {
    "en": "👋 Hello there! *Voicy* is a voice recognition bot that converts all voice messages and audio files (.ogg, .flac, .wav, .mp3) it gets into text.\n\n*Voicy* supports three voice recognition engines: wit.ai (free), Yandex SpeechKit (free) and Google Speech (not free). Initialy it's set to use wit.ai but you can switch to Google Speech or Yandex SpeechKit anytime in /engine\n\nFor starters, you got *60 seconds* of Google Speech voice recognition for free. If you will need more Google Speech time, you can always purchase it here:\nhttps://pay.voicybot.com/$[1]\n\n...or just use free wit.ai or Yandex SpeechKit forever 😀",
    "ru": "👋 Привет! *Voicy* — это бот, который переводит в текст все голосовые сообщения и аудио файлы (.ogg, .flac, .wav, .mp3), которые получает.\n\n*Voicy* поддерживает три движка распознавания речи: wit.ai (бесплатный), Яндекс SpeechKit (бесплатный) и Google Speech (платный). Изначально бот выбирает бесплатный wit.ai, но вы можете сменить движок на Google Speech или Яндекс SpeechKit, используя команду /engine.\n\nДля ознакомления, мы даем вам *60 секунд* Google Speech в подарок. Если вам понадобится больше секунд Google Speech, вы всегда можете приобрести их по ссылке:\nhttps://pay.voicybot.com/$[1]\n\n...или просто используйте бесплатный wit.ai или Яндекс SpeechKit 😀",
    "es": "👋 ¡Hola! *Voicy* es un bot de reconocimiento de voz que convierte todos los mensajes de voz y archivos de audio (.ogg, .flac, .wav, .mp3) a texto.\n\n*Voicy* admite tres motores de reconocimiento de voz: wit.ai (gratuito), Yandex SpeechKit (gratuito) y Google Speech (pago). Inicialmente está configurado para usar wit.ai, pero puedes cambiarlo y utilizar Google Speech o Yandex SpeechKit en cualquier momento en /engine\n\npara principiantes, tienes *60 segundos* de reconocimiento de voz de Google Speech gratis. Si necesitas más tiempo de Google Speech, puedes comprarlo aquí:\nhttps://pay.voicybot.com/$[1]\n\n... o simplemente utilizar wit.ai o Yandex SpeechKit de forma gratuita para siempre 😀",
    "ch": "👋 您好! Voicy 是一个语音识别程序，可转换所有语音消息和音频文件 (.ogg， .flac， .wav， .mp3) 为文本格式。\n\nVoicy 支持三种语音识别引擎: wit.ai (免费)， Yandex SpeechKit (免费) 以及 Google Speech (收费)。 它的起始设置状态为使用 wit.ai，但您随时可在 /engine 下将其切换为 Google Speech 或 Yandex SpeechKit\n\n对于新用户，您可免费使用60秒 Google Speech 语音识别。如果你需要更多 Google Speech 时间，您随时可以在这里购买：\nhttps://pay.voicybot.com/$[1]\n\n...或者永久使用免费的 wit.ai 或 Yandex SpeechKit 😀"
  },
  "👋 Hello there! *Voicy* is a voice recognition bot that converts all voice messages and audio files (.ogg, .flac, .wav, .mp3) it gets into text.\n\n*Voicy* supports three voice recognition engines: wit.ai (free), Yandex SpeechKit (free) and Google Speech (not free). Initialy it's set to use wit.ai but you can switch to Google Speech or Yandex SpeechKit anytime in /engine\n\nSo far you have *$[1] seconds* of Google Speech voice recognition left. If you will need more Google Speech time, you can always purchase it here:\nhttps://pay.voicybot.com/$[2]\n\n...or just use free wit.ai or Yandex SpeechKit forever 😀": {
    "en": "👋 Hello there! *Voicy* is a voice recognition bot that converts all voice messages and audio files (.ogg, .flac, .wav, .mp3) it gets into text.\n\n*Voicy* supports three voice recognition engines: wit.ai (free), Yandex SpeechKit (free) and Google Speech (not free). Initialy it's set to use wit.ai but you can switch to Google Speech or Yandex SpeechKit anytime in /engine\n\nSo far you have *$[1] seconds* of Google Speech voice recognition left. If you will need more Google Speech time, you can always purchase it here:\nhttps://pay.voicybot.com/$[2]\n\n...or just use free wit.ai or Yandex SpeechKit forever 😀",
    "ru": "👋 Привет! *Voicy* — это бот, который переводит в текст все голосовые сообщения и аудио файлы (.ogg, .flac, .wav, .mp3), которые получает.\n\n*Voicy* поддерживает три движка распознавания речи: wit.ai (бесплатный), Яндекс SpeechKit (бесплатный) и Google Speech (платный). Изначально бот выбирает бесплатный wit.ai, но вы можете сменить движок на Google Speech или Яндекс SpeechKit, используя команду /engine.\n\nУ вас осталось *$[1] секунд* Google Speech в этом чате. Если вам понадобится больше секунд Google Speech, вы всегда можете приобрести их по ссылке:\nhttps://pay.voicybot.com/$[2]\n\n...или просто используйте бесплатный wit.ai или Яндекс SpeechKit 😀",
    "es": "👋 ¡Hola! *Voicy* es un bot de reconocimiento de voz que convierte todos los mensajes de voz y archivos de audio (.ogg, .flac, .wav, .mp3) a texto.\n\n*Voicy* admite tres motores de reconocimiento de voz: wit.ai (gratuito), Yandex SpeechKit (gratuito) y Google Speech (pago). Inicialmente está configurado para usar wit.ai pero puedes cambiarlo y utilizar Google Speech o Yandex SpeechKit en cualquier momento en /engine\n\nTendrás *$[1] segundos* de reconocimiento de voz de Google Speech. Si necesitas más tiempo de Google Speech, siempre puedes comprarlo aquí:\nhttps://pay.voicybot.com/$[2]\n\n ... o simplemente utilizar wit.ai o Yandex SpeechKit de manera gratuita para siempre 😀",
    "ch": "👋 您好! Voicy 是一个语音识别程序，可转换所有语音消息和音频文件 (.ogg， .flac， .wav， .mp3) 为文本格式。\n\nVoicy 支持三种语音识别引擎: wit.ai (免费)， Yandex SpeechKit (免费) 以及 Google Speech (收费)。 它的起始设置状态为使用 wit.ai，但您随时可在 /engine 下将其切换为 Google Speech 或 Yandex SpeechKit\n\n目前您还可免费使用 $[1] 秒 Google Speech语音识别。 如果你需要更多 Google Speech 时间，您随时可以在这里购买：\nhttps://pay.voicybot.com/$[2]\n\n...或者永久使用免费的 wit.ai 或 Yandex SpeechKitr 😀"
  },
  "🎉 Unfortunately, being the most superior voice recognition engine, Google Speech is not free. If you want to keep using free wit.ai or Yandex SpeechKit for voice recognition, no need to do anything. However, if you want to use Google Speech you have to cover it's costs.\n\nThis chat has *$[1] seconds* of Google Speech voice recognition left.\n\nAnybody can buy more Google Speech seconds for the price of *$0.4 per 200 seconds* here:\nhttps://pay.voicybot.com/$[2].": {
    "en": "🎉 Unfortunately, being the most superior voice recognition engine, Google Speech is not free. If you want to keep using free wit.ai or Yandex SpeechKit for voice recognition, no need to do anything. However, if you want to use Google Speech you have to cover it's costs.\n\nThis chat has *$[1] seconds* of Google Speech voice recognition left.\n\nAnybody can buy more Google Speech seconds for the price of *$0.4 per 200 seconds* here:\nhttps://pay.voicybot.com/$[2].",
    "ru": "🎉 К сожалению, Google Speech — более точный переводчик речи в текст — не бесплатен. Если вы хотите и дальше использовать бесплатные wit.ai или Яндекс SpeechKit — просто проигнорируйте это сообщение. Однако если вы хотите использовать Google Speech, вам придётся оплатить стоимость распознавания.\n\nУ этого чата осталось еще *$[1] секунд* Google Speech.\n\nКто угодно может купить больше секунд Google Speech по цене *$0.4 за 200 секунд* по ссылке:\nhttps://pay.voicybot.com/$[2].",
    "es": "🎉 Desafortunadamente, pese a ser el mejor motor de reconocimiento de voz, Google Speech no es gratuito. Si quieres seguir usando wit.ai o Yandex SpeechKit gratuitos para reconocimiento de voz, no tienes necesidad de hacer nada. Sin embargo, si quieres usar Google Speech, tienes que cubrir sus costos. \n\nEste chat tiene *$[1] segundos* de reconocimiento de voz de Google Speech.\n\nCualquier persona puede comprar más segundos de Google Speech por el precio de *$0.4 por cada 200 segundos* aquí: \nhttps://pay.voicybot.com/$[2].",
    "ch": "🎉 很遗憾的是，作为最优秀的语音识别引擎，Google Speech并非免费。如果您想继续使用免费的 wit.ai 或 Yandex SpeechKit进行语音识别，则不需要做任何事情。然而，如果您想继续使用 Google Speech，您必须得承担起费用。\n\n本次对话还剩 $[1] 秒 Google Speech语音识别时间。\n\n任何人都可以在这里以每200秒0.4美元的价格购买更多的谷歌语音秒数\nhttps://pay.voicybot.com/$[2]。"
  },
  "🎉 Unfortunately, being the most superior voice recognition engine, Google Speech is not free. If you want to switch to free wit.ai or Yandex SpeechKit for voice recognition, please do so in /engine. However, if you want to stick to Google Speech you have to cover it's costs.\n\nThis chat has *$[1] seconds* of Google Speech voice recognition left.\n\nAnybody can buy more Google Speech seconds for the price of *$0.4 per 200 seconds* here:\nhttps://pay.voicybot.com/$[2].": {
    "en": "🎉 Unfortunately, being the most superior voice recognition engine, Google Speech is not free. If you want to switch to free wit.ai or Yandex SpeechKit for voice recognition, please do so in /engine. However, if you want to stick to Google Speech you have to cover it's costs.\n\nThis chat has *$[1] seconds* of Google Speech voice recognition left.\n\nAnybody can buy more Google Speech seconds for the price of *$0.4 per 200 seconds* here:\nhttps://pay.voicybot.com/$[2].",
    "ru": "🎉 К сожалению, Google Speech — более точный переводчик речи в текст — не бесплатен. Если вы хотите перейти на бесплатный wit.ai или Яндекс SpeechKit — используйте команду /engine. Однако если вы хотите продолжить использовать Google Speech, вам придётся оплатить стоимость распознавания.\n\nУ этого чата осталось еще *$[1] секунд* Google Speech.\n\nКто угодно может купить больше секунд Google Speech по цене *$0.4 за 200 секунд* по ссылке:\nhttps://pay.voicybot.com/$[2].",
    "es": "🎉 Desafortunadamente, pese a ser el mejor motor de reconocimiento de voz, Google Speech no es gratuito. Si quieres cambiar a wit.ai o Yandex SpeechKit gratuitos para reconocimiento de voz, por favor hazlo en /engine. Sin embargo, si quieres quedarte con Google Speech tienes que cubrir sus costos. \n\nEste chat tiene *$[1] segundos* de reconocimiento de voz de Google Speech.\n\nCualquier persona puede comprar más segundos de Google Speech por el precio de *$0.4 por cada 200 segundos* aquí :\nhttps://pay.voicybot.com/$[2].",
    "ch": "🎉 很遗憾的是，作为最优秀的语音识别引擎，Google Speech并非免费。如果您想切换为免费的 wit.ai 或 Yandex SpeechKit进行语音识别，请在 /engine 下进行操作。 然而，如果您坚持使用 Google Speech，您必须得承担起费用。\n\n本次对话还剩 $[1] 秒 Google Speech语音识别时间。\n\n任何人都可以在这里以每200秒0.4美元的价格购买更多的谷歌语音秒数：\nhttps://pay.voicybot.com/$[2]。"
  },
  "😮 It looks like this chat has *no more seconds* of Google Speech voice recognition left! But no worries — we have automatically switched you to the free wit.ai so that no voice messages are getting lost. Don't forget to setup your /language.\n\nHowever if you would like to keep using Google Speech you will have to switch back in /engine and cover it's costs 💰\n\nAnybody can buy more seconds for the price of *$0.4 per 200 seconds* here:\nhttps://pay.voicybot.com/$[1].": {
    "en": "😮 It looks like this chat has *no more seconds* of Google Speech voice recognition left! But no worries — we have automatically switched you to the free wit.ai so that no voice messages are getting lost. Don't forget to setup your /language.\n\nHowever if you would like to keep using Google Speech you will have to switch back in /engine and cover it's costs 💰\n\nAnybody can buy more seconds for the price of *$0.4 per 200 seconds* here:\nhttps://pay.voicybot.com/$[1].",
    "ru": "😮 Похоже, у этого чата больше *нет секунд* Google Speech! Но ничего страшного — мы автоматически перевели вас на бесплатный wit.ai, чтобы не потерять ни одного голосового сообщения. Обязательно установите язык командой /language!\n\nОднако если вы хотите продолжить использовать Google Speech, вам нужно сменить движок командой /engine и оплатить стоимость распознавания 💰\n\nКто угодно может купить больше секунд Google Speech по цене *$0.4 за 200 секунд* по ссылке:\nhttps://pay.voicybot.com/$[1].",
    "es": "😮 ¡Parece que este chat no tiene *más segundos* de reconocimiento de voz de Google Speech! Pero no te preocupes – te hemos cambiado automáticamente a wit.ai gratuito para que no se pierda ningún mensajes de voz. No olvides configurar tu /language.\n\nSin embargo, si quieres seguir usando Google Speech deberás cambiar nuevamente en /engine y cubrir sus costos 💰\n\nCualquier persona puede comprar más segundos de Google Speech por el precio de *$0.4 por cada 200 segundos* aquí \nhttps://pay.voicybot.com/$[1].",
    "ch": "😮 看上去本次对话的 Google Speech语音识别 没有更多秒数 剩余！ 但不用担心 — 我们已自动将您切换为免费的 wit.ai，这样就不会有语音消息丢失。不要忘记设置您的 /language。\n\n然而，如果您想继续使用 Google Speech，您得在 /engine 下将其切换回来并承担其费用 💰\n\n任何人都可以在这里以每200秒0.4美元的价格购买更多的谷歌语音秒数：\nhttps://pay.voicybot.com/$[1]。"
  },
  "😎 *Voicy* converts speech to text from any voice messages and audio files (.ogg, .flac, .wav, .mp3) it receives. You can either talk to *Voicy* in the private chat or add it to a group.\n\n/help — Shows this message 😱\n/engine — Lets you pick a voice recognition engine: wit.ai (free), Yandex SpeechKit (free) or Google Speech (not free) ⚙\n/language — Lets you pick a voice recognition language 📣\n/balance — Shows how many Google Speech voice recognition seconds are left for this chat 🎉\n/files — Toggles if the bot should attempt to convert audio files or just ignore them 📁\n/silent — Toggles silent mode when no extra messages like `Voice recognition is initiated` are sent 😶\n\nLike this bot? Leave a review here: https://telegram.me/storebot?start=voicybot\n\nAddress any concerns and questions to my creator — @borodutch 🦄": {
    "en": "😎 *Voicy* converts speech to text from any voice messages and audio files (.ogg, .flac, .wav, .mp3) it receives. You can either talk to *Voicy* in the private chat or add it to a group.\n\n/help — Shows this message 😱\n/engine — Lets you pick a voice recognition engine: wit.ai (free), Yandex SpeechKit (free) or Google Speech (not free) ⚙\n/language — Lets you pick a voice recognition language 📣\n/balance — Shows how many Google Speech voice recognition seconds are left for this chat 🎉\n/files — Toggles if the bot should attempt to convert audio files or just ignore them 📁\n/silent — Toggles silent mode when no extra messages like `Voice recognition is initiated` are sent 😶\n\nLike this bot? Leave a review here: https://telegram.me/storebot?start=voicybot\n\nAddress any concerns and questions to my creator — @borodutch 🦄",
    "ru": "😎 *Voicy* переводит в текст все голосовые сообщения, которые получает. Вы можете говорить с ботом напрямую или добавить его в группу.\n\n/help — Показать это сообщение 😱\n/engine — Выбрать движок распознавания речи: wit.ai (бесплатный), Яндекс SpeechKit (бесплатный) или Google Speech (платный) ⚙\n/language — Выбрать язык распознавания речи 📣\n/balance — Посмотреть, сколько секунд Google Speech осталось 🎉\n/files — Включить или выключить распознавание аудио файлов 📁\n/silent — Включить или выключить тихий режим, когда бот не посылает сообщения типа `Распознавание речи инициировано` 😶\n\nНравится бот? Оставьте свой отзыв по ссылке: https://telegram.me/storebot?start=voicybot\n\nВопросы и предложения направляйте моему создателю — @borodutch 🦄",
    "es": "😎 *Voicy* convierte discurso a texto desde cualquier mensaje de voz y archivos de audio (.ogg, .flac, .wav, .mp3) que reciba. Puede hablar con *Voicy* en un chat privado o agregarlo a un grupo.\n\n/help - Muestra este mensaje 😱\n/engine - Permite elegir un motor de reconocimiento de voz: wit.ai (gratuito), Yandex SpeechKit (gratuito) o Google Speech (pago) ⚙\n/language - Permite seleccionar el idioma de reconocimiento de voz 📣\n/balance - Muestra cuántos segundos de reconocimiento de voz de Google Speech quedan para este chat 🎉\n/files - Cambia si el bot intenta convertir archivos de audio o simplemente ignorarlos 📁\n/silent - Cambia el modo silencioso cuando no se envían mensajes adicionales como \"Reconocimiento de voz\" 😶\n\nTe gusta este bot? Deja un comentario aquí: https://telegram.me/storebot?start=voicybot\n\nEnviar cualquier duda o consulta a mi creador - @borodutch 🦄",
    "ch": "😎 Voicy 可将其收到的任何语音消息和音频文件 (.ogg， .flac， .wav，.mp3) 转换为文本。 您可以私聊模式与 Voicy 交谈，也可将其添加到群组。\n\n/help — 显示本条消息 😱\n/engine — 可让您挑选一种语音识别引擎： wit.ai (免费)、 Yandex SpeechKit (免费)或 Google Speech (收费) ⚙\n/language — 可让您挑选一种语言识别语言 📣\n/balance — 显示本次对话还剩多少 Google Speech 语音识别秒数 🎉\n/files — 如果软件应尝试转换音频文件或将其忽略时进行切换 📁\n/silent — 当没有 `语音识别已启用` 之类的额外消息发送时切换为静默模式 😶\n\n赞本软件？在这里评论：https://telegram.me/storebot?start=voicybot\n\n向我的创建者阐述疑问和问题 — @borodutch 🦄"
  },
  "😎 *Voicy* converts speech to text from any voice messages and audio files (.ogg, .flac, .wav, .mp3) it receives. You can either talk to *Voicy* in the private chat or add it to a group.\n\n/help — Shows this message 😱\n/engine — Lets you pick a voice recognition engine: wit.ai (free), Yandex SpeechKit (free) or Google Speech (not free) ⚙\n/language — Lets you pick a voice recognition language 📣\n/balance — Shows how many Google Speech voice recognition seconds are left for this chat 🎉\n/lock — Toggles lock or unlock of non-admins using commands 🔑\n/files — Toggles if the bot should attempt to convert audio files or just ignore them 📁\n/silent — Toggles silent mode when no extra messages like `Voice recognition is initiated` are sent 😶\n\nLike this bot? Leave a review here: https://telegram.me/storebot?start=voicybot\n\nAddress any concerns and questions to my creator — @borodutch 🦄": {
    "en": "😎 *Voicy* converts speech to text from any voice messages and audio files (.ogg, .flac, .wav, .mp3) it receives. You can either talk to *Voicy* in the private chat or add it to a group.\n\n/help — Shows this message 😱\n/engine — Lets you pick a voice recognition engine: wit.ai (free), Yandex SpeechKit (free) or Google Speech (not free) ⚙\n/language — Lets you pick a voice recognition language 📣\n/balance — Shows how many Google Speech voice recognition seconds are left for this chat 🎉\n/lock — Toggles lock or unlock of non-admins using commands 🔑\n/files — Toggles if the bot should attempt to convert audio files or just ignore them 📁\n/silent — Toggles silent mode when no extra messages like `Voice recognition is initiated` are sent 😶\n\nLike this bot? Leave a review here: https://telegram.me/storebot?start=voicybot\n\nAddress any concerns and questions to my creator — @borodutch 🦄",
    "ru": "😎 *Voicy* переводит в текст все голосовые сообщения, которые получает. Вы можете говорить с ботом напрямую или добавить его в группу.\n\n/help — Показать это сообщение 😱\n/engine — Выбрать движок распознавания речи: wit.ai (бесплатный), Яндекс SpeechKit (бесплатный) или Google Speech (платный) ⚙\n/language — Выбрать язык распознавания речи 📣\n/balance — Посмотреть, сколько секунд Google Speech осталось 🎉\n/lock — Включить или выключить доступ не-админов к командам бота 🔑\n/files — Включить или выключить распознавание аудио файлов 📁\n\n/silent — Включить или выключить тихий режим, когда бот не посылает сообщения типа `Распознавание речи инициировано` 😶\n\nНравится бот? Оставьте свой отзыв по ссылке: https://telegram.me/storebot?start=voicybot\n\nВопросы и предложения направляйте моему создателю — @borodutch 🦄",
    "es": "😎 *Voicy* convierte discurso a texto desde cualquier mensaje de voz y archivos de audio (.ogg, .flac, .wav, .mp3) que reciba. Puede hablar con *Voicy* en un chat privado o agregarlo a un grupo.\n\n/help - Muestra este mensaje 😱\n/engine - Permite elegir un motor de reconocimiento de voz: wit.ai (gratuito), Yandex SpeechKit (gratuito) o Google Speech (pago) ⚙\n/language - Permite seleccionar el idioma de reconocimiento de voz  📣\n/balance - Muestra cuántos segundos de reconocimiento de voz de Google Speech quedan para este chat 🎉\n/lock - Cambia el bloqueo o desbloqueo de los no administradores que usan comandos 🔑\n/files - El bot debería intentar convertir archivos de audio o simplemente ignorarlos 📁\n/silent - Cambia el modo silencioso cuando no se envían mensajes adicionales como “Reconocimiento de voz” 😶\n\nTe gusta este bot? Deja un comentario aquí: https://telegram.me/storebot?start=voicybot\n\nEnviar cualquier consulta duda o consulta a mi creador - @borodutch 🦄",
    "ch": "😎 Voicy 可将其收到的任何语音消息和音频文件 (.ogg， .flac， .wav， .mp3) 转换为文本。 您可以私聊模式与Voicy 交谈，也可将其添加到群组。\n\n/help — 显示本条消息 😱\n/engine — 可让您挑选一种语音识别引擎： wit.ai (免费)、 Yandex SpeechKit (免费)或 Google Speech (收费) ⚙\n/language — 可让您挑选一种语言识别语言 📣\n/balance — 显示本次对话还剩多少 Google Speech 语音识别秒数 🎉\n/lock — 使用命令进行非管理人员的锁定或解锁切换 🔑\n/files — 如果软件应尝试转换音频文件或将其忽略时进行切换 📁\n/silent — 当没有 `语音识别已启用` 之类的额外消息发送时切换为静默模式 😶\n\n赞本软件？在这里评论：https://telegram.me/storebot?start=voicybot\n\n向我的创建者阐述疑问和问题 — @borodutch 🦄"
  },
  "👋 Please, select the engine of speech recognition. Google Speech is more accurate, private (your messages will never go public), support audio longer than 50 seconds, but not free. Yandex SpeechKit is pretty accurate, free, private and most of the time supports audio longer than 50 seconds, but has limited list of languages. Wit.ai is less accurate, public (your messages go to wit.ai public database), free, but doesn't support audio longer than 50 seconds.\n\nHere is the list of the supported languages:\n\n*wit.ai*: `Albanian, Arabic, Bengali, Bosnian, Bulgarian, Burmese, Catalan, Chinese, Croatian, Czech, Danish, Dutch, English, Estonian, Finnish, French, Georgian, German, Greek, Hebrew, Hindi, Hungarian, Icelandic, Indonesian, Italian, Japanese, Korean, Latin, Lithuanian, Macedonian, Malay, Norwegian, Persian, Polish, Portuguese, Romanian, Russian, Serbian, Slovak, Slovenian, Spanish, Swahili, Swedish, Tagalog, Tamil, Thai, Turkish, Ukrainian and Vietnamese`.\n\n*Yandex SpeechKit*: `Russian, English, Turkish, Ukrainian`.\n\n*Google Speech*: `Afrikaans, Indonesian, Malay, Catalan, Czech, Danish, German, English (Australia, Canada, United Kingdom, India, Ireland, New Zealand, Philippines, South Africa, United States), Spanish (Argentina, Bolivia, Chile, Colombia, Costa Rica, Ecuador, El Salvador, Spain, United States, Guatemala, Honduras, Mexico, Nicaragua, Panama, Paraguay, Peru, Puerto Rico, Dominican Republic, Uruguay, Venezuela), Basque,  Filipino, French, Galician, Croatian, Zulu, Icelandic, Italian, Lithuanian, Hungarian, Dutch, Norwegian Bokmål, Polish, Portuguese (Brazil, Portugal), Romanian, Slovak, Slovenian, Finnish, Swedish, Vietnamese, Turkish, Greek, Bulgarian, Russian, Serbian, Ukrainian, Hebrew, Arabic (Israel, Jordan, United Arab Emirates, Bahrain, Algeria, Saudi Arabia, Iraq, Kuwait, Morocco, Tunisia, Oman, State of Palestine, Qatar, Lebanon, Egypt), Persian, Hindi, Thai, Korean, Mandarin (Traditional, Taiwan; Simplified, Hong Kong; Simplified, China), Cantonese (Traditional, Hong Kong), Japanese (Japan)`.": {
    "en": "👋 Please, select the engine of speech recognition. Google Speech is more accurate, private (your messages will never go public), support audio longer than 50 seconds, but not free. Yandex SpeechKit is pretty accurate, free, private and most of the time supports audio longer than 50 seconds, but has limited list of languages. Wit.ai is less accurate, public (your messages go to wit.ai public database), free, but doesn't support audio longer than 50 seconds.\n\nHere is the list of the supported languages:\n\n*wit.ai*: `Albanian, Arabic, Bengali, Bosnian, Bulgarian, Burmese, Catalan, Chinese, Croatian, Czech, Danish, Dutch, English, Estonian, Finnish, French, Georgian, German, Greek, Hebrew, Hindi, Hungarian, Icelandic, Indonesian, Italian, Japanese, Korean, Latin, Lithuanian, Macedonian, Malay, Norwegian, Persian, Polish, Portuguese, Romanian, Russian, Serbian, Slovak, Slovenian, Spanish, Swahili, Swedish, Tagalog, Tamil, Thai, Turkish, Ukrainian and Vietnamese`.\n\n*Yandex SpeechKit*: `Russian, English, Turkish, Ukrainian`.\n\n*Google Speech*: `Afrikaans, Indonesian, Malay, Catalan, Czech, Danish, German, English (Australia, Canada, United Kingdom, India, Ireland, New Zealand, Philippines, South Africa, United States), Spanish (Argentina, Bolivia, Chile, Colombia, Costa Rica, Ecuador, El Salvador, Spain, United States, Guatemala, Honduras, Mexico, Nicaragua, Panama, Paraguay, Peru, Puerto Rico, Dominican Republic, Uruguay, Venezuela), Basque,  Filipino, French, Galician, Croatian, Zulu, Icelandic, Italian, Lithuanian, Hungarian, Dutch, Norwegian Bokmål, Polish, Portuguese (Brazil, Portugal), Romanian, Slovak, Slovenian, Finnish, Swedish, Vietnamese, Turkish, Greek, Bulgarian, Russian, Serbian, Ukrainian, Hebrew, Arabic (Israel, Jordan, United Arab Emirates, Bahrain, Algeria, Saudi Arabia, Iraq, Kuwait, Morocco, Tunisia, Oman, State of Palestine, Qatar, Lebanon, Egypt), Persian, Hindi, Thai, Korean, Mandarin (Traditional, Taiwan; Simplified, Hong Kong; Simplified, China), Cantonese (Traditional, Hong Kong), Japanese (Japan)`.",
    "ru": "👋 Выберите движок распознавания речи. Google Speech — более точный, приватный (ваши сообщения никогда не станут достоянием общественности), поддерживает аудио длиннее 50 секунд, но не бесплатный. Яндекс SpeechKit — поддерживает аудио длиннее 50 секунд, беслпатный, приватный, но с ограниченным количеством языков. Wit.ai — менее точный, публичный (данные хранятся в открытом доступе на wit.ai), не поддерживает аудио длиннее 50 секунд, но бесплатный.\n\nСписки поддерживаемых языков:\n\n*wit.ai*: `Albanian, Arabic, Bengali, Bosnian, Bulgarian, Burmese, Catalan, Chinese, Croatian, Czech, Danish, Dutch, English, Estonian, Finnish, French, Georgian, German, Greek, Hebrew, Hindi, Hungarian, Icelandic, Indonesian, Italian, Japanese, Korean, Latin, Lithuanian, Macedonian, Malay, Norwegian, Persian, Polish, Portuguese, Romanian, Russian, Serbian, Slovak, Slovenian, Spanish, Swahili, Swedish, Tagalog, Tamil, Thai, Turkish, Ukrainian, Vietnamese`.\n\n*Яндекс SpeechKit*: `Russian, English, Turkish, Ukrainian`.\n\n*Google Speech*: `Afrikaans, Indonesian, Malay, Catalan, Czech, Danish, German, English (Australia, Canada, United Kingdom, India, Ireland, New Zealand, Philippines, South Africa, United States), Spanish (Argentina, Bolivia, Chile, Colombia, Costa Rica, Ecuador, El Salvador, Spain, United States, Guatemala, Honduras, Mexico, Nicaragua, Panama, Paraguay, Peru, Puerto Rico, Dominican Republic, Uruguay, Venezuela), Basque,  Filipino, French, Galician, Croatian, Zulu, Icelandic, Italian, Lithuanian, Hungarian, Dutch, Norwegian Bokmål, Polish, Portuguese (Brazil, Portugal), Romanian, Slovak, Slovenian, Finnish, Swedish, Vietnamese, Turkish, Greek, Bulgarian, Russian, Serbian, Ukrainian, Hebrew, Arabic (Israel, Jordan, United Arab Emirates, Bahrain, Algeria, Saudi Arabia, Iraq, Kuwait, Morocco, Tunisia, Oman, State of Palestine, Qatar, Lebanon, Egypt), Persian, Hindi, Thai, Korean, Mandarin (Traditional, Taiwan; Simplified, Hong Kong; Simplified, China), Cantonese (Traditional, Hong Kong), Japanese (Japan)`.",
    "es": "👋 Por favor, selecciona el motor del reconocimiento de voz: Google Speech es más preciso, privado (tus mensajes nunca serán públicos), soporta audios de más de 50 segundos, pero no es gratuito. Yandex SpeechKit es bastante preciso, gratuito, privado y casi siempre es compatible audios de más de 50 segundos, pero tiene una lista limitada de idiomas. Wit.ai es menos preciso, público (tus mensajes van a la base de datos pública de wit.ai), es gratuito pero no es compatible con audios de más de 50 segundos. \n\nEsta es la lista de idiomas disponibles:\n\n*wit.ai*: `albanés, árabe, bengalí, bosnio, búlgaro, birmano, catalán, chino, croata, checo, danés, holandés, inglés, estonio, Finlandés, francés, georgiano, griego, hebreo, hindi, húngaro, islandés, indonesio, italiano, japonés, coreano, latín, lituano, macedonio, malayo, noruego, persa, polaco, Portugués, rumano, ruso, serbio, eslovaco, esloveno, español, swahili, sueco, tagalo, tamil, tailandés, turco, ucraniano y vietnamita`.\n\n*Yandex SpeechKit*: `Ruso, Inglés, Turco, Ucraniano`.\n\n*Google Speech*: `Español, Sueco, Tagalo, Tamil, Afrikáans, Indonesio, Malayo, Catalán, Checo, Danés, Alemán, Inglés (Australia, Canadá, Reino Unido, India, Irlanda, Nueva Zelanda, Filipinas, Sudáfrica, Estados Unidos), Español (Argentina, Bolivia, Chile, Colombia, Costa Ecuador, Ecuador, El Salvador, España, Guatemala, Honduras, México, Nicaragua, Panamá, Paraguay, Perú, Puerto Rico, República Dominicana, Uruguay, Venezuela), Vasco, Filipino, Gallego, Croata, Zulú, Islandés, Italiano, Lituano, Húngaro, Holandés, Noruego Bokmål, Polaco, Portugués (Brasil, Portugal),Rumano, Esloveno, Esloveno, Finlandés, Sueco, Vietnamita, Turco, Griego, Búlgaro, Ruso, Serbio, Ucraniano, Hebreo, Árabe (Israel, Jordania, Emiratos Árabes Unidos, Bahreiní, Argelia, Iraq, Kuwait, Marruecos, Túnez , Tailandia, Coreano, Mandarín (Tradicional, Taiwán, Simplificado, Hong Kong, Simplificado, China), Cantonés (Tradicional, Hong Kong), Japonés (Japón)`.",
    "ch": "👋 请选择语音识别引擎。 Google Speech更准确、保密性更强（您的消息永远不会公开），支持长于50秒的音频，但不免费。 Yandex SpeechKit相当准确，免费，保密性好，大多数时间支持长于50秒的音频，但只有有限的语言列表选项。 Wit.ai 不够准确， 是公开的 (您的消息会上传到 wit.ai 公共数据库)，免费，但不支持长于50秒的音频。\n\n这里是支持的语言列表：\n\nwit.ai: `阿尔巴尼亚语、阿拉伯语、孟加拉语、波斯尼亚语、保加利亚语、缅甸语、加泰罗尼亚语、汉语、克罗地亚语、捷克语、丹麦语、荷兰语、英语、爱沙尼亚语、芬兰语、法语、格鲁吉亚语、德语、希腊语、希伯来语、印地语、匈牙利语、冰岛语、印尼语、意大利语、日语、韩语、拉丁语、立陶宛语、马其顿语、马来语、挪威语、波斯语、波兰语、葡萄牙语、罗马尼亚语、俄语、塞尔维亚语、斯洛伐克语、斯洛文尼亚语、西班牙语、斯瓦希里语、瑞典语、他加禄语、泰米尔语、泰语、土耳其语、乌克兰语、越南语`。\n\nYandex SpeechKit: `俄语、英语、土耳其语、乌克兰语`。\n\nGoogle Speech: `南非荷兰语、印尼语、马来语、加泰罗尼亚语、捷克语、丹麦语、德语、英语（澳大利亚、加拿大、英国、印度、爱尔兰、新西兰、菲律宾、南非、美国）、西班牙语（阿根廷、玻利维亚、智利、哥伦比亚、哥斯达黎加、厄瓜多尔、萨尔瓦多、西班牙、美国、瓜地马拉、洪都拉斯、墨西哥、尼加拉瓜巴拿马、巴拉圭、秘鲁、波多黎各、多米尼加共和国、乌拉圭、委内瑞拉）、巴斯克语、菲律宾语、法语、加利西亚语、克罗地亚语、祖鲁语、冰岛语、意大利语、立陶宛语、匈牙利语、荷兰语、书面挪威语、波兰语、葡萄牙语（巴西、葡萄牙）、罗马尼亚语、斯洛伐克语、斯洛文尼亚语、芬兰语、瑞典语、越南语、土耳其语、希腊语、俄语、保加利亚语、塞尔维亚语、乌克兰语、希伯来语、阿拉伯语（以色列、约旦、阿拉伯联合酋长国、巴林、阿尔及利亚、沙特阿拉伯、伊拉克、科威特、摩洛哥、突尼斯、阿曼、巴勒斯坦国、卡塔尔、黎巴嫩、埃及）、波斯语、印地语、泰语、韩语、汉语（繁体及简体：台湾、香港；简化：中国）、粤语（繁体：香港）、日语（日本）`。"
  },
  "👍 Now *Voicy* uses *$[1]* in this chat. Thank you! Don't forget to set /language.": {
    "en": "👍 Now *Voicy* uses *$[1]* in this chat. Thank you! Don't forget to set /language.",
    "ru": "👍 Теперь *Voicy* использует *$[1]* в этом чате. Спасибо! Не забудьте установить /language (язык).",
    "es": "👍 Ahora *Voicy* utiliza *$[1]* en este chat. ¡Gracias!, No te olvides configurar /language.",
    "ch": "👍 现在 Voicy 在本次对话中使用 $[1]。谢谢！请不要忘记设置 /language。"
  },
  "👋 Please select the language of speech recognition": {
    "en": "👋 Please select the language of speech recognition",
    "ru": "👋 Выберите язык распознавания речи",
    "es": "👋 Por favor, seleccione el idioma de reconocimiento de voz",
    "ch": "👋 请选择语音识别的语言"
  },
  "👋 Please select the language of speech recognition for $[1].": {
    "en": "👋 Please, select the language of speech recognition for $[1].",
    "ru": "👋 Выберите язык распознавания речи для $[1].",
    "es": "👋 Por favor, seleccione el idioma de reconocimiento de voz para $[1].",
    "ch": "👋 请为 $[1]选择语音识别的语言。"
  },
  "👋 Please select the language of speech recognition for wit.ai.": {
    "en": "👋 Please, select the language of speech recognition for wit.ai.",
    "ru": "👋 Выберите язык распознавания речи для wit.ai.",
    "es": "👋 Por favor, seleccione el idioma de reconocimiento de voz para wit.ai.",
    "ch": "👋 请为 wit.ai选择语音识别的语言。"
  },
  "👍 Now *Voicy* speaks *$[1]* (wit.ai) in this chat. Thank you!": {
    "en": "👍 Now *Voicy* speaks *$[1]* (wit.ai) in this chat. Thank you!",
    "ru": "👍 Теперь *Voicy* понимает *$[1]* (wit.ai) в этом чате. Спасибо!",
    "es": "👍 Ahora *Voicy* habla *$[1]* (wit.ai) en este chat. ¡Gracias!",
    "ch": "👍 现在 Voicy 在本次对话中说 $[1] (wit.ai) 。谢谢！"
  },
  "👋 Please select the language of speech recognition for Google Speech.": {
    "en": "👋 Please, select the language of speech recognition for Google Speech.",
    "ru": "👋 Выберите язык распознавания речи для Google Speech.",
    "es": "👋 Por favor, seleccione el idioma de reconocimiento de voz para Google Speech.",
    "ch": "👋 请为 Google Speech选择语音识别的语言。"
  },
  "👍 Now *Voicy* speaks *$[1]* (Google Speech) in this chat. Thank you!": {
    "en": "👍 Now *Voicy* speaks *$[1]* (Google Speech) in this chat. Thank you!",
    "ru": "👍 Теперь *Voicy* понимает *$[1]* (Google Speech) в этом чате. Спасибо!",
    "es": "👍  Ahora *Voicy* habla *$[1]* (Google Speech) en este chat. ¡Gracias!",
    "ch": "👍 现在 Voicy 在本次对话中说 $[1] (Google Speech) 。谢谢！"
  },
  "👍 Now *Voicy* speaks *$[1]* (Yandex SpeechKit) in this chat. Thank you!": {
    "en": "👍 Now *Voicy* speaks *$[1]* (Yandex SpeechKit) in this chat. Thank you!",
    "ru": "👍 Теперь *Voicy* понимает *$[1]* (Яндекс SpeechKit) в этом чате. Спасибо!",
    "es": "👍 Ahora *Voicy* habla *$[1]* (Yandex SpeechKit) en este chat. ¡Gracias!",
    "ch": "👍 现在 Voicy 在本次对话中说 $[1] (Yandex SpeechKit) 。谢谢！"
  },
  "😮 You didn't have enough seconds of Google Speech voice recognition left to convert this voice message! But no worries — we have automatically switched you to the free wit.ai so that no voice messages are getting lost. Don't forget to setup your /language.": {
    "en": "😮 You didn't have enough seconds of Google Speech voice recognition left to convert this voice message! But no worries — we have automatically switched you to the free wit.ai so that no voice messages are getting lost. Don't forget to setup your /language.",
    "ru": "😮 У вас не хватило секунд Google Speech для распознавания этого голосового сообщения! Но ничего страшного — мы автоматически перели ваш чат на бесплатный wit.ai, чтобы не потерять ни одного сообщения. Не забудьте указать ваш язык командой /language!",
    "es": "😮 ¡No tenías suficientes segundos de reconocimiento de voz de Google Speech para convertir este mensaje de voz!, pero no te preocupes: te hemos cambiado automáticamente a wit.ai para que no se pierda ningún mensajes de voz. No te olvides de configurar tu /language.",
    "ch": "😮 你已没有足够的 Google Speech 语音识别秒数来转换本条语音消息！但不用担心 — 我们已自动将您切换为免费的 wit.ai，这样就不会有语音消息丢失e 。不要忘记设置您的 /language。"
  },
  "_👮 I can't recognize voice messages larger than 20 megabytes_": {
    "en": "_👮 I can't recognize voice messages larger than 20 megabytes_",
    "ru": "_👮 Я не умею распознавать аудио тяжелее 20 мегабайт_",
    "es": "_👮 No puedo reconocer mensajes de voz mayores a 20 megabytes_",
    "ch": "_👮 我无法识别大于20GB的语音消息_"
  },
  "_🦄 Voice recognition is initiated..._": {
    "en": "_🦄 Voice recognition is initiated..._",
    "ru": "_🦄 Распознавание речи инициировано..._",
    "es": "_🦄 Se inicia el reconocimiento de voz..._",
    "ch": "_🦄 语音识别已启用..._"
  },
  "_👮 Please, speak clearly, I couldn't recognize that_": {
    "en": "_👮 Please, speak clearly, I couldn't recognize that._",
    "ru": "_👮 Пожалуйста, говорите четче, у меня не получилось распознать вашу речь._",
    "es": "_👮 Por favor, habla con claridad, no pude reconocer eso_",
    "ch": "_👮 请说清晰些，我无法识别那是什么_"
  },
  "_👮 I couldn't recognize that_": {
    "en": "_👮 I couldn't recognize that._",
    "ru": "_👮 У меня не получилось распознать речь._",
    "es": "_👮 No pude reconocer eso_",
    "ch": "_👮 我无法识别那是什么_"
  },
  "😅 Looks like you have already applied Product Hunt discount. Your first 100,000 Google Speech seconds are 50% off. Enjoy! 🐱": {
    "en": "😅 Looks like you have already applied Product Hunt discount. Your first 100,000 Google Speech seconds are 50% off. Enjoy! 🐱",
    "ru": "😅 Похоже, вы уже использовали скидку с Product Hunt. Ваши первые 100,000 Google Speech секунд уже на 50% дешевле. Спасибо! 🐱",
    "es": "😅 Parece que ya has aplicado el descuento de Product Hunt. Los primeros 100.000 segundos de Google Speech tiene 50% de descuento. ¡Disfruta! 🐱",
    "ch": "😅 看样子您已申请产品搜寻优惠。您的前 100,000秒 Google Speech 可优惠 50%。 好好享用吧！ 🐱"
  },
  "🔥 Look who applied Product Hunt discount to @voicybot! Enjoy your first 100,000 Google Speech seconds at 50% the price! 🦄": {
    "en": "🔥 Look who applied Product Hunt discount to @voicybot! Enjoy your first 100,000 Google Speech seconds at 50% the price! 🦄",
    "ru": "🔥 Смотрите, кто использовал скидку с Product Hunt в @voicybot! Наслаждайтесь первыми 100,000 секундами распознавания Google Speech с 50% скидкой! 🦄",
    "es": "🔥 ¡Mira quién aplicó el descuento de Product Hunt a @voicybot! ¡Disfruta de tus primeros 100.000 segundos de Google Speech al 50% del precio! 🦄",
    "ch": "🔥 看看谁 @voicybot申请了产品搜寻优惠！ 以50%的优惠价格享受您的前 100,000秒 Google Speech ！ 🦄"
  },
  "🔑 Great! *Voicy* will now respond only to command calls sent by *admins* in this chat.": {
    "en": "🔑 Great! *Voicy* will now respond only to command calls sent by *admins* in this chat.",
    "ru": "🔑 Чудно! *Voicy* теперь реагирует только на команды, посланные *админами*, в этом чате.",
    "es": "🔑 ¡Genial! *Voicy* ahora responderá sólo a las llamadas de comando enviadas por *admins* en este chat.",
    "ch": "🔑 好极了！ Voicy 现在将只对本次对话中由 管理员 发出的命令调用进行响应。"
  },
  "🔑 Great! *Voicy* will now respond only to command calls from *anyone* in this chat.": {
    "en": "🔑 Great! *Voicy* will now respond only to command calls from *anyone* in this chat.",
    "ru": "🔑 Чудно! *Voicy* теперь реагирует на команды, посланные *любыми пользователями*, в этом чате.",
    "es": "🔑 ¡Genial! *Voicy* ahora responderá sólo a las llamadas de comando de *cualquier persona* en este chat.",
    "ch": "🔑 好极了！ Voicy 现在将只对本次对话中由 任何人 发出的命令调用进行响应。"
  },
  "😶 Magnificent! *Voicy* will now work in *silent mode*: it will not send any messages to the chat except for the actual voice transcriptions.": {
    "en": "😶 Magnificent! *Voicy* will now work in *silent mode*: it will not send any messages to the chat except for the actual voice transcriptions.",
    "ru": "😶 Великолепно! *Voicy* теперь работает в *тихом режиме*: больше никаких сообщений, кроме перевода речи в текст.",
    "es": "😶 ¡Magnífico! *Voicy* ahora funcionará en *modo silencioso*: no enviará ningún mensaje al chat, excepto las transcripciones de voz reales.",
    "ch": "😶 了不起！ Voicy 现在将以 静默模式工作： 除了实际语音转录外，它将不会发送任何消息到该对话中。"
  },
  "😏 Magnificent! *Voicy* will now work in *usual mode*: it will send `Voice recognition is initiated` messages right after it receives voice messages.": {
    "en": "😏 Magnificent! *Voicy* will now work in *usual mode*: it will send `Voice recognition is initiated` messages right after it receives voice messages.",
    "ru": "😏 Великолепно! *Voicy* теперь работает в *обычном режиме*: бот будет посылать промежуточное сообщение `Распознавание речи инициировано` после каждого полученного голосового сообщения.",
    "es": "😏 ¡Magnífico! *Voicy* funcionará ahora en *modo habitual*: enviará mensajes de \"Reconocimiento de voz iniciado” inmediatamente luego de recibir mensajes de voz",
    "ch": "😏 了不起！ Voicy 现在将以 静默模式工作：它将在收到语音消息后发送消息 `语音识别已启用`。"
  },
  "_👮 Wit.ai cannot recognize voice messages longer than 50 seconds_": {
    "en": "_👮 Wit.ai cannot recognize voice messages longer than 50 seconds_",
    "ru": "_👮 Wit.ai не понимает аудио длиннее 50 секунд_",
    "es": "_👮 Wit.ai no puede reconocer mensajes de voz de más de 50 segundos_",
    "ch": "_👮 Wit.ai 无法识别长于50秒的语音消息_"
  },
  "📁 Wonderful! *Voicy* will *ignore* all audio files in this chat since now.": {
    "en": "📁 Wonderful! *Voicy* will *ignore* all audio files in this chat since now.",
    "ru": "📁 Отлично! *Voicy* теперь будет *игнорировать* все аудио файлы в этом чате.",
    "es": "📁 ¡Maravilloso! Desde ahora *Voicy ignorará* todos los archivos de audio en este chat.",
    "ch": "📁 棒极了！ Voicy 将从现在开始 忽略 本次对话中的所有音频文件。"
  },
  "📁 Wonderful! *Voicy* will *try to recognize* all audio files in this chat since now.": {
    "en": "📁 Wonderful! *Voicy* will *try to recognize* all audio files in this chat since now.",
    "ru": "📁 Отлично! *Voicy* теперь будет *пробовать распознать* все аудио файлы в этом чате.",
    "es": "📁 ¡Maravilloso! Desde ahora *Voicy* *intentará reconocer* todos los archivos de audio en este chat.",
    "ch": "📁 棒极了！Voicy 将从现在开始 尝试识别 本次对话中的所有音频文件。"
  }
}